site_name: dog-school
site_url: https://asyncon.github.io/dog-school/
site_author: asyncon
site_description: Dog School

repo_name: asyncon/dog-school
repo_url: https://github.com/asyncon/dog-school
edit_uri: ""

copyright: Copyright &copy; 2022 asyncon

theme:
  name: material
  palette:
    - scheme: default
      primary: indigo
      accent: orange
      media: "(prefers-color-scheme: light)"
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: deep orange
      accent: blue
      media: "(prefers-color-scheme: dark)"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - meta
  - admonition
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed
